In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_excel("../data/Data Set - PaySwift.xlsx")

In [9]:
df.head()

,User ID,Age,Loan Amount (GHS),Repayment Status,Feature Used Most,Monthly Transactions,Churned?,Default Risk (1-5)
0,1001,28,2000,Late Payment,Mobile Payments,12,No,4
1,1002,35,5000,On-Time,Budgeting Tool,25,No,1
2,1003,22,1000,Defaulted,Loan Services,5,Yes,5
3,1004,40,3500,On-Time,Savings Tracker,18,No,2
4,1005,30,4000,Late Payment,Investment Advice,9,Yes,3

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   User ID               100 non-null    int64
 1   Age                   100 non-null    int64
 2   Loan Amount (GHS)     100 non-null    int64
 3   Repayment Status      99 non-null     str
 4   Feature Used Most     84 non-null     str
 5   Monthly Transactions  100 non-null    int64
 6   Churned?              100 non-null    str
 7   Default Risk (1-5)    100 non-null    int64
dtypes: int64(5), str(3)
memory usage: 6.4 KB

In [11]:
df.describe()

,User ID,Age,Loan Amount (GHS),Monthly Transactions,Default Risk (1-5)
count,100.000000,100.000000,100.000000,100.000000,100.000000
mean,1050.500000,33.170000,3432.500000,12.520000,3.280000
std,29.011492,8.657402,2048.704629,8.197659,1.484465
min,1001.000000,19.000000,800.000000,1.000000,1.000000
25%,1025.750000,26.000000,1537.500000,5.750000,2.000000
50%,1050.500000,32.500000,3150.000000,11.000000,3.000000
75%,1075.250000,40.000000,4825.000000,19.000000,5.000000
max,1100.000000,50.000000,8000.000000,30.000000,5.000000

In [12]:
df['Feature Used Most'] = df['Feature Used Most'].fillna('No Usage')

In [13]:
df.head()

,User ID,Age,Loan Amount (GHS),Repayment Status,Feature Used Most,Monthly Transactions,Churned?,Default Risk (1-5)
0,1001,28,2000,Late Payment,Mobile Payments,12,No,4
1,1002,35,5000,On-Time,Budgeting Tool,25,No,1
2,1003,22,1000,Defaulted,Loan Services,5,Yes,5
3,1004,40,3500,On-Time,Savings Tracker,18,No,2
4,1005,30,4000,Late Payment,Investment Advice,9,Yes,3